# Generated by Django 5.0 on 2024-01-01 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0002_sample_analysisend_sample_analysissart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='analysisSart',
            new_name='analysisStart',
        ),
    ]
